rust/template/Cargo.toml, rust/template/bin/pipe.rs, rust/template/bin/test, rust/template/src/lib.rs
This does require updating the docker image,
as the changes depend on Rust 1.15 in the builder image.
This has no effect on published algos, but does break
compilation of existing rust algorithms.
The impact is quite small (namely myself, @zeryx,
and a small handful of unpublished, stale test algos)
The work-around is to just update dependencies
and switch from rustc-serialize to serde
which is often just an attribute change except in
cases of complex custom JSON parsing.
The improvements in this change include:
- Using the new 2.0 client
- Error messages should be more thorough ("caused by" chain)
- Adds algorithm testing (previously held back for ergonomic reasons)
- Switches to serde serialization/deserialization which is faster and significantly more flexible/configurable (and finally …
=> upgrade rust template and client

docker/Dockerfile.single-builder
a version of cuda remains so that packages like pycuda can be installed via pip since they build against the cuda headers
=> Remove driver from builder image

r/template/bin/rip.py
I'm not sure if this will result in errors compiliing some R algorithms that did in fact get packages installed correctly, however this will definitively prevent erroneous "build successful" for R algorithms when in fact a package was never installed.  R will emit warning messages like:
```
ERROR: dependency ‘dplyr’ is not available for package ‘dbplyr’
* removing ‘/usr/local/lib/R/site-library/dbplyr’
```
or 
```
Warning message:                                                            
package ‘nlme’ is not available (for R version 3.3.3)
```
on package installation, which are clearly more than warnings
=> Attempt to load the library after installing it so that an error will be thrown in the event of a 'warning' that the package couldn't be installed

r/template/bin/rip.py
do some string parsing for http installs and skip validation for github installs since parsing that would be tough.
idk, it's kind of janky but I've been able to install packages via HTTP locally again and would like to get this out into test to validate a few more examples (copied script over to a build machine in test already but would like to validate it "for real").   I figured this sort of weird parsing was probably the best option to still have some guarantee that package install was successful
=> Tokens for installing from http/github don't match package name

libraries/python37/Dockerfile
In testing there seems to be some sporadic errors when trying to get the GPG key when installing python, trying to use a different keyserver address here based on some google-fu
=> Use a different keyserver to hopefully prevent sporadic errors seen in our build environment

languages/Dockerfile.builder.j2, languages/Dockerfile.compile.j2, languages/Dockerfile.runner.j2, libraries/python3-buildtime/Dockerfile, libraries/python3-runtime/Dockerfile
The change requires a bump in the version of kaniko in use (https://github.com/algorithmiaio/kaniko/pull/2) but I also have a couple questions to resolve via committee here:
1. The builder/runner images already end with the `USER algo` lines so having it in the compile dockerfile is a bit unnecessary
2. Choice of 2222 was totally arbitrary but didn't know if others were aware of this - https://github.com/algorithmiaio/langpacks/blob/master/languages/Dockerfile.builder.j2#L10.  I chose it because it seemed like a good idea to not be the same as users that might already exist on our system, and because we've had confusing situations in the past with local development where something works for one person and not another person because the UID would be 1000 or something, but some people's …
=> Use numeric uids/gids instead of named user so that user id lookups aren't required and therefore can use the kaniko cache effectively

languages/Dockerfile.builder.j2, languages/Dockerfile.runner.j2, libraries/python3-runtime/Dockerfile, libraries/python36/Dockerfile, libraries/python36/install.sh, libraries/pytorch-1.0.0/Dockerfile, libraries/pytorch-1.0.0/context/requirements.txt, libraries/pytorch-1.0.0/install.sh, libraries/tensorflow-gpu-1.12/Dockerfile, libraries/tensorflow-gpu-1.12/context/requirements.txt
Also adding a small tweak to the python runtime so pip-installed binaries are available on PATH.  I will be testing this in test and might have to submit tweaks but it's a little easier to test this using test infra if I merge first
=> Copy Python37 install to Python36 directory

languages/Dockerfile.compile.j2
I feel like this is a little unfortunate (and could still use $ALGO_UID in the USER statement but felt like may as well be consistent here)
=> Some builder backends don't resolve environment variables in chown commands, so we have to use the numeric id

languages/Dockerfile.compile.j2, languages/python2/config.json, languages/python3/config.json, libraries/python2-buildtime/Dockerfile, libraries/python3-buildtime/Dockerfile
Bin/build security fix for IPA algos; build script is now placed in and used from `/usr/local/bin` rather than the working directory
Work to be done
- Legit filter function
=> Platform 2297 ipa bin build security

languages/Dockerfile.builder.j2, languages/Dockerfile.runner.j2, libraries/csharp-dotnet-core2/Dockerfile
reduced imports to bare minimum, since we use ubuntu 16.04 as a base image, the microsoft base images are incompatible - however this method works fine as is.
=> ALGO-579 simplified imports for dotnet sdk installation

libraries/python27/Dockerfile, libraries/python36/Dockerfile, libraries/python37/Dockerfile
This should help reduce the number of times building image fails by a large amount.  I tested this out by replacing the first sks-keyserver with a junk value that guaranteed would fail and the build still succeeded.
=> Add ubuntu keyserver as a backup in case the sks-keyserver fails

libraries/tensorrt-6.0-cuda10.0/Dockerfile, libraries/tensorrt-6.0-cuda10.0/context/install, templates/tensorrt-6.0-cuda10.0/algorithmia.conf, templates/tensorrt-6.0-cuda10.0/requirements.txt, templates/tensorrt-6.0-cuda10.0/src/__ALGO__.py, templates/tensorrt-6.0-cuda10.0/src/__ALGO___test.py, templates/tensorrt-6.0-cuda10.0/src/auxillary.py
added and verified tensorRT support with onnx template.
My validator tool currently doesn't support gpus or algo keys, so please run the following command to build the package:
`./tools/packageset_validator.py -b nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04 -g python3 -s python37 -d tensorrt-6.0-cuda10.0 -t dependency -n tensorrt-6.0-cuda10.0`
and then when that fails, run the final image with the following
`docker run -it --runtime=nvidia -p 9999:9999 -e ALGORITHMIA_API_KEY='YOUR_API_KEY_HERE' 773e57916fcb`, replacing `773e57916fcb` with your final image hash as an output from `docker images`.
**Requires NVIDIA Docker to be installed and configured to test**
=> ALGO-596 tensorrt support

tools/packageset_validator.py
This PR adds nvidia/cuda support to docker runtimes when requested by the user. Simply add the `--nvidia-support` flag, and ensure that you're base image extends/is `nvidia/cuda:xxx`.
=> Algo-XXX add nvidia support to validator

templates/tensorflow-gpu-1.12/src/__ALGO__.py, templates/tensorflow-gpu-1.13/src/__ALGO__.py, templates/tensorflow-gpu-1.14/src/__ALGO__.py, templates/tensorflow-gpu-2.0/src/__ALGO__.py, templates/tensorflow-gpu-2.1/src/__ALGO__.py
Changed the tensorflow 1.x & 2.x templates to limits GPU usage up to 30% of the GPU.
To test, you can copy over the hello world templates on PROD, compile & try to run the example input.
I've verified the new templates on all packagesets except for tensorflow 2.1.x.
It seems that tf-2.1.x doesn't support CUDA 10.2, it specifically requires CUDA 10.1, so you'll get an error when you run the new template.
I've made a separate PR for that on `stagetools` which will make `tf-2.1.x` use `CUDA 10.1` instead of `CUDA 10.2` here: https://github.com/algorithmiaio/stagetools/pull/1005
Relevant Github issue can be found [here](https://github.com/tensorflow/tensorflow/issues/34759).
=> Limit tf gpu usage

src/langrunner.rs, src/langserver.rs, src/main.rs, src/message.rs
This seems to get the information plumbed through, the error message still shows up as `exited with code 1` but the stderr/stdout get populated and we've previously had code that will scan for that one error message and instead report back stderr.
My thought is that it could make sense to just tack the stderr/stdout directly to the `error message` during unexpected exit but this at least solves the immediate problem (with a few modifications in other components)
=> Attempt to fixup the last of the compile errors via guess and check

src/langserver.rs
Apparently this used to be handled externally - https://github.com/algorithmiaio/langpacks/commit/519859017443d2f6d6dd79962a447da74c94cb8c 
But that is no longer the case.  In a more abstract sense exiting langserver when the algorithm process is the only logical thing to do since it can't respond to any more API requests.
Validated that the errant behavior seen over the weekend no longer occurs.
=> Exit langserver after sending notification in the event that the algorithm process exits

languages/Dockerfile.compile.j2
Builds were failing due to `/opt/algorithmiaio/mounted-scripts/customize-container.sh: not found`, so copying the scripts from the build context directory's location to the expected execution location.
Validated that builds completed successfully in cluster
=> Scripts need to be copied from the build's context directory into the expected location

languages/Dockerfile.compile.j2
Without this change the customize-container.sh script ends up thinking there's no custom certificates :(
=> Need to copy to full directory

languages/Dockerfile.compile.j2, libraries/tensorflow-gpu-2.3/Dockerfile, templates/tensorflow-gpu-2.3/algorithmia.conf, templates/tensorflow-gpu-2.3/requirements.txt, templates/tensorflow-gpu-2.3/src/__ALGO__.py, templates/tensorflow-gpu-2.3/src/__ALGO___test.py, tools/template_manager.py
This PR includes a new Tensorflow 2.3. package support for python 3.7. To test this, please go to the langpacks directory on a gpu enabled computer (deepPurple is a good bet) and run the following command:
`$ ./tools/environment_validator.py -b nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04 -g python3 -s python37 -d tensorflow-gpu-2.3 -t dependency -n tensorflow-gpu-2.3 --nvidia-support 1`
after that's done, on a separate tab (same machine) provide the following input:
`$ curl localhost:9999 -H 'Content-Type: application/json' -d '{
"matrix_a": [[0, 1], [1, 0]],
"matrix_b": [[25, 25], [11, 11]]
}'`
If this returns successfully, then you've been able to verify the functionality of the algorithm and package set
=> ALGO-789 Tensorflow 2.3.X support

java/template/pom.xml, languages/java11/template/pom.xml, languages/scala-2/template/build.sbt, scala/template/build.sbt
Prior to this, without setting the maven mirrors we would get errors like:
```
[ERROR] Plugin org.apache.maven.plugins:maven-resources-plugin:2.3 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.3: Could not transfer artifact org.apache.maven.plugins:maven-resources-plugin:pom:2.3 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.3/maven-resources-plugin-2.3.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. -> [Help 1]
```
This sets the needed variables for pluginRepositories as well, which should still be overridden in appropriate maven mirrors/proxy settings in the …
=> Set default repository and pluginRepositories that will point at HTTPS maven

templates/mleap_databricks/src/main/scala/com/algorithmia/Algorithm.scala
oof good catch @kennydaniel, key has thankfully been deprecated immediately after the push; but I forgot to remove the key from the template.
=> removed deprecated API key from template

libraries/python38/Dockerfile, libraries/python39/Dockerfile
Hey James, this branch is adding Python38 support with the Dockerfile under `libraries`, installing Python v3.8.6 with pip v20.2.4.
Tested on deeppurple for 2 different algorithms but will continue testing this further. For now it works okay for
1. An algorithm that's failing on the marketplace on python37 env:
```
./tools/environment_validator.py -b ubuntu:16.04 -g python3 -s python38 -t dependency -n albert_classification -c 1 -k sim0/CA0mCa6Xz3FAkyoHb45G5I1
```
verified with: 
```
curl localhost:9999 -H 'Content-Type: application/json' -d '{ "texts": "asli" }'
```
2. Testing with the usual TF template on CPU: 
```
./tools/environment_validator.py -b ubuntu:16.04 -g python3 -s python38 -d tensorflow-cpu-2.3 -t dependency -n tensorflow-cpu-2.3 -c 1
```
verified with: 
```
curl …
```
=> Added python38 (3.8.6) support with pip v20.2.4

java/template/pom.xml, languages/java11/template/pom.xml
See https://algorithmia.atlassian.net/browse/PSE-540?atlOrigin=eyJpIjoiN2ZlYzgyZWE0OTFiNGQyNWFlMDViY2QzYjhkZTA2MmIiLCJwIjoiaiJ9 for more details.
Updating the java client library versions to remove the Maven warnings trying to pull problematic dependencies sbt-pgp and sbt-sonatype. 
Feel free to add any additional reviewers as necessary.
=> PSE-540 Update algorithmia-java-extras and algorithmia-client versions

libraries/anaconda35/Dockerfile, libraries/anaconda49/Dockerfile, libraries/python27/Dockerfile, libraries/python36/Dockerfile, libraries/python37/Dockerfile, libraries/python38/Dockerfile
URGENT:
lzma support is a blocker for one of our customers.
` ./tools/environment_validator.py -g python[x] -s python[x] -t language -n python[x]`
^ please test the construction of each version of python that we support:
* python27
* python36
* python37
* python38
Please also verify with a simple `import pandas as pd` that we no longer get the lzma warning, to sanity check that the `lzma` package is installed.
=> ALGO-890 added lzma to all python base images
